@startuml
class TAD {
  tadId : xsd:string (PK)
  startPosition : xsd:integer
  endPosition : xsd:integer
}

class Chromosome {
  chromosome : xsd:string (PK)
}

class SourceMethod {
  sourceMethod : xsd:string (PK)
}

class CellType {
  cellType : xsd:string (PK)
}

class CallingMethod {
  callingMethod : xsd:string (PK)
}

class Resolution {
  resolution : xsd:string (PK)
}

class SourceFile {
  sourceFile : xsd:string (PK)
}

class Database {
  databaseName : xsd:string (PK)
}

Chromosome "1" -- "0..*" TAD : locates
SourceMethod "1" -- "0..*" TAD : derives
CellType "1" -- "0..*" TAD : characterizes
CallingMethod "1" -- "0..*" TAD : identifies
Resolution "1" -- "0..*" TAD : defines
SourceFile "1" -- "0..*" TAD : recordedIn
Database "1" -- "0..*" TAD : storedIn
@enduml