@startuml
class TAD {
  +tadId : xsd:string (PK)
  chromosome : xsd:string
  startPosition : xsd:integer
  endPosition : xsd:integer
}

class CellType {
  +cellType : xsd:string (PK)
}

class SourceMethod {
  +sourceMethod : xsd:string (PK)
}

class CallingMethod {
  +callingMethod : xsd:string (PK)
}

class Resolution {
  +resolution : xsd:string (PK)
}

class SourceFile {
  +sourceFile : xsd:string (PK)
}

class Database {
  +databaseName : xsd:string (PK)
}

class TADObservation {
  +tadId : xsd:string (PK) (FK)
  +cellType : xsd:string (PK) (FK)
  +sourceMethod : xsd:string (PK) (FK)
  +callingMethod : xsd:string (PK) (FK)
  +resolution : xsd:string (PK) (FK)
  +sourceFile : xsd:string (PK) (FK)
  +databaseName : xsd:string (PK) (FK)
}

TAD "1" -- "0..*" TADObservation : observed_as
CellType "1" -- "0..*" TADObservation : in_cell_type
SourceMethod "1" -- "0..*" TADObservation : derived_from_source_method
CallingMethod "1" -- "0..*" TADObservation : identified_by_calling_method
Resolution "1" -- "0..*" TADObservation : at_resolution
SourceFile "1" -- "0..*" TADObservation : recorded_in_source_file
Database "1" -- "0..*" TADObservation : stored_in_database
@enduml